export { default as EventCard } from "./Event/ui/EventCard/EventCard.tsx";
export {
  EventForm,
  type BaseEventFormData,
  type EventFormData,
} from "./Event/ui/EventForm/EventForm.tsx";

export {
  getEvents,
  type Event,
  type getEventsResponse,
} from "./Event/api/getEvents.ts";

export { getTags, type Tag } from "./Tag";

//TODO: добавить index.ts для каждой сущности

export {
  blockReorderingReducer,
  createEvent,
  deleteEvent,
  editEventSettings,
  eventNameReducer,
  eventQueries,
  getEditingEventData,
  getEditingEventSettings,
  getEventsHistory,
  getFavoritesEvents,
  getNextStage,
  getPlayerInfo,
  getUserEvents,
  joinEvent,
  selectBlockReorderingState,
  selectEventName,
  setBlockReorderingState,
  setName,
  useEditingEventData,
  useGroups,
  useJoinCodeData,
  useJoinEvent,
  useJoinRequiredFields,
  usePersonalEvents,
  usePlayerStats,
  useRole,
  useUpdateBlocksOrder,
  type BlockItemData,
  type BlockStage,
  type ClientGroup,
  type CreateEventData,
  type CreateEventResponse,
  type EditEventSettingsResponse,
  type EditingEventSettings,
  type EndStage,
  type getEditingEventDataResponse,
  type GetNextStageResponse,
  type Group,
  type GroupStats,
  type JoinDetails,
  type QueryFnType,
  type ServerGroup,
  type TaskItem,
  type TaskOption,
  type TaskStage,
  type TaskStageData,
  type UseGroupsQueryData,
  type UseJoinCodeDataResult,
  type UseJoinEventResponse,
  type UserStats,
} from "./Event";

export {
  BlockCard,
  blockQueries,
  deleteBlock,
  getBlockSettings,
  getConditions,
  getTasks,
  selectTasksReorderingState,
  setTasksReorderingState,
  tasksReorderingReducer,
  updateBlockSettings,
  useBlockSettings,
  useConditions,
  useTasks,
  useUpdateBlockName,
  useUpdateBlockSettings,
  useUpdateTasksOrder,
  type BlockSettings,
  type Condition,
  type GetConditionsResponse,
  type GetTasksResponse,
  type TaskItemData,
  type UpdateBlockData,
  type UseConditionsData,
} from "./Block";

export {
  createTask,
  deleteTask,
  getEditorTaskData,
  TaskForm,
  taskQueries,
  TaskView,
  updateTask,
  useEditorTaskData,
  type ClientOption,
  type CreateTaskResponse,
  type GetEditorTaskDataResponse,
  type ServerOption,
  type UpdateTaskResponse,
} from "./Task";

export {
  ConditionForm,
  createCondition,
  updateCondition,
  useUpdateGroups,
  type ConditionData,
  type CreateConditionResponse,
  type UpdateConditionResponse,
} from "./Condition";

export {
  getNotifications,
  NotificationCard,
  notificationQueries,
  useDeleteNotification,
  useNotifications,
  type CustomNotification,
  type EventEndExtra,
  type EventStartExtra,
  type GetNotificationsQueryData,
  type NotificationType,
} from "./Notification";
