apiVersion: v1
kind: Service
metadata:
  name: eduplay-frontend
  namespace: eduplay
spec:
  selector:
    app: eduplay-frontend
  ports:
    - name: frontend
      port: 8080
      targetPort: 80
      protocol: TCP
  type: ClusterIP
